$NetBSD$

--- configure.cmake.orig	2014-03-14 19:07:26.000000000 +0000
+++ configure.cmake
@@ -433,7 +433,10 @@ CHECK_FUNCTION_EXISTS (getpassphrase HAV
 CHECK_FUNCTION_EXISTS (getpwnam HAVE_GETPWNAM)
 CHECK_FUNCTION_EXISTS (getpwuid HAVE_GETPWUID)
 CHECK_FUNCTION_EXISTS (getrlimit HAVE_GETRLIMIT)
+# Haiku have not fully implemented rusage
+if (NOT HAIKU)
 CHECK_FUNCTION_EXISTS (getrusage HAVE_GETRUSAGE)
+endif (NOT HAIKU)
 CHECK_FUNCTION_EXISTS (getwd HAVE_GETWD)
 CHECK_FUNCTION_EXISTS (gmtime_r HAVE_GMTIME_R)
 CHECK_FUNCTION_EXISTS (initgroups HAVE_INITGROUPS)
