ALLOW_VULNERABLE_PACKAGES= yes
SKIP_LICENSE_CHECK= yes
PKG_REGISTER_SHELLS= yes
PREFER_PKGSRC= yes
_OPSYS_PREFER.getopt= native
#PKG_DEVELOPER=yes
NO_CHECKSUM=yes
#FIX_SYSTEM_HEADERS= yes

#${TOOLS_PREFIX.digest}=/boot/home/pkg
