#Pkgsrc Custom Settings - Check Total = 2
.include "/boot/home/pkg/etc/pkgsrc/CustomFeatures.mk"
.include "/boot/home/pkg/etc/pkgsrc/CustomFileLocations.mk"

# Settings For All Packages - Check Total = 13
.include "/boot/home/pkg/etc/pkgsrc/global/Add-Makefile-Library.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/Builtin.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/CFLAGS.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/Compiler.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/CONFIGURE_ARGS_ENV.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/Default-Packages.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/Fonts.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/LDFLAGS.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/PKG_DEFAULT_OPTIONS.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/Remove-Makefile-Library.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/SUBST_CLASSES.mk"
.include "/boot/home/pkg/etc/pkgsrc/global/Substitute-Makefile-Library.mk"

# Settings For Specific Packages - Check Total = 17
.include "/boot/home/pkg/etc/pkgsrc/package/Add-Makefile-Library.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Autoconf-CPPFLAGS.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/CheckPermissions.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/CompileTool.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/CONFIGURE_ARGS_ENV.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/CFLAGS.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Haiku-Misc.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Hard-Links.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Include-Dependency-Headers.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/LDFLAGS.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/LIBTOOL-SHARED.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Libs.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/PKG_OPTIONS.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Remove-Compiler-Setting.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Remove-Makefile-Library.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/SUBST_CLASSES.mk"
.include "/boot/home/pkg/etc/pkgsrc/package/Substitute-Makefile-Library.mk"
